# Generated by Django 5.2.17 on 2026-09-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, help_text='Nama Organisasi / Perusahaan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='photo',
            field=models.URLField(blank=True, help_text='Masukkan link URL foto/logo di sini', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(help_text='Posisi / Role', max_length=255),
        ),
    ]
