# Generated by Django 5.2.17 on 2026-09-14 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_experience_thumbnail_experience_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Contoh: Backend Development', max_length=255)),
                ('skill', models.CharField(help_text='Contoh: Django, SpringBoot, Node.js', max_length=255)),
                ('image', models.URLField(blank=True, help_text='Masukkan link URL icon/gambar interest', null=True)),
            ],
        ),
    ]
